[package]
name = "autotiling-rs"
version = "0.1.3"
authors = ["Jason Nader <jason.nader@protonmail.com>"]
edition = "2018"

[dependencies]
swayipc = "2.7"

[dependencies.clap]
version = "2.33"
default-features = false
